[target.riscv64gc-unknown-none-elf]
linker = "clang"
rustflags =["-C", "link-arg=-Tsrc/kernel/kernel.ld"]
runner = """
qemu-system-riscv64 -machine virt -bios default -nographic -serial mon:stdio --no-reboot \
    -kernel
"""